# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photomanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='httpurl',
            field=models.URLField(max_length=1000),
        ),
    ]
